/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.Ghanem.basiclibrary.lib.src.main.java.com.Ghanem;

import java.util.Arrays;

public class App {

    public static void main(String[] args) {
       lab02 test = new lab02();

        int[] arr = test.roll(5);
        System.out.println(Arrays.toString(arr));


        int[] arr2 = {1, 1, 2, 3, 4};
        boolean b = test.containsDuplicates(arr2);
        System.out.println(b);


        int[] arr3 = {90, 80, 50, 70, 90, 95, 85, 79};
        System.out.println(test.CalculatingAverages(arr3));


        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {80, 54, 70, 53, 59, 57, 70},
                {65, 56, 55, 52, 55, 62, 57}
        };

        int[] arr4 = test.arraysOfArrays(weeklyMonthTemperatures);
        System.out.println(Arrays.toString(arr4));
    }
}
